<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Decision Tree | Movie Box Office</title>
  <meta name="description" content="Chapter 4 Decision Tree | Movie Box Office" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Decision Tree | Movie Box Office" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Decision Tree | Movie Box Office" />
  
  
  

<meta name="author" content="Hongwei Zha" />


<meta name="date" content="2023-04-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-regression.html"/>
<link rel="next" href="random-forest.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">IMDB</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Proposal</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data"><i class="fa fa-check"></i><b>1.1</b> Data</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#modeling-goal"><i class="fa fa-check"></i><b>1.2</b> Modeling Goal</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#models"><i class="fa fa-check"></i><b>1.3</b> Models</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-pre-processing.html"><a href="data-pre-processing.html"><i class="fa fa-check"></i><b>2</b> Data pre-processing</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-pre-processing.html"><a href="data-pre-processing.html#data-dictionary"><i class="fa fa-check"></i><b>2.1</b> Data Dictionary</a></li>
<li class="chapter" data-level="2.2" data-path="data-pre-processing.html"><a href="data-pre-processing.html#data-summary"><i class="fa fa-check"></i><b>2.2</b> Data Summary</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-pre-processing.html"><a href="data-pre-processing.html#data-statistics"><i class="fa fa-check"></i><b>2.2.1</b> Data Statistics</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-pre-processing.html"><a href="data-pre-processing.html#visualizing-missing-values"><i class="fa fa-check"></i><b>2.2.2</b> Visualizing Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-pre-processing.html"><a href="data-pre-processing.html#box-office-vs-genre"><i class="fa fa-check"></i><b>2.3</b> Box Office Vs Genre</a></li>
<li class="chapter" data-level="2.4" data-path="data-pre-processing.html"><a href="data-pre-processing.html#box-office-vs-rating-certificate"><i class="fa fa-check"></i><b>2.4</b> Box Office Vs Rating &amp; Certificate</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>3</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="linear-regression.html"><a href="linear-regression.html#model-fitting"><i class="fa fa-check"></i><b>3.1</b> Model Fitting</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="linear-regression.html"><a href="linear-regression.html#model-summary"><i class="fa fa-check"></i><b>3.1.1</b> Model Summary</a></li>
<li class="chapter" data-level="3.1.2" data-path="linear-regression.html"><a href="linear-regression.html#check-linearity"><i class="fa fa-check"></i><b>3.1.2</b> Check Linearity</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="linear-regression.html"><a href="linear-regression.html#model-evaluation"><i class="fa fa-check"></i><b>3.2</b> Model Evaluation</a></li>
<li class="chapter" data-level="3.3" data-path="linear-regression.html"><a href="linear-regression.html#model-interpretation"><i class="fa fa-check"></i><b>3.3</b> Model Interpretation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="linear-regression.html"><a href="linear-regression.html#partial-dependence-plot"><i class="fa fa-check"></i><b>3.3.1</b> Partial Dependence Plot</a></li>
<li class="chapter" data-level="3.3.2" data-path="linear-regression.html"><a href="linear-regression.html#local-interpretable-model-agnostic-explanations-lime"><i class="fa fa-check"></i><b>3.3.2</b> Local Interpretable Model-agnostic Explanations (LIME)</a></li>
<li class="chapter" data-level="3.3.3" data-path="linear-regression.html"><a href="linear-regression.html#shapley-additive-explanations"><i class="fa fa-check"></i><b>3.3.3</b> Shapley Additive Explanations</a></li>
<li class="chapter" data-level="3.3.4" data-path="linear-regression.html"><a href="linear-regression.html#feature-importance"><i class="fa fa-check"></i><b>3.3.4</b> Feature Importance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="decision-tree.html"><a href="decision-tree.html"><i class="fa fa-check"></i><b>4</b> Decision Tree</a>
<ul>
<li class="chapter" data-level="4.1" data-path="decision-tree.html"><a href="decision-tree.html#model-fitting-1"><i class="fa fa-check"></i><b>4.1</b> Model Fitting</a></li>
<li class="chapter" data-level="4.2" data-path="decision-tree.html"><a href="decision-tree.html#model-visualization"><i class="fa fa-check"></i><b>4.2</b> Model Visualization</a></li>
<li class="chapter" data-level="4.3" data-path="decision-tree.html"><a href="decision-tree.html#model-evaluation-1"><i class="fa fa-check"></i><b>4.3</b> Model Evaluation</a></li>
<li class="chapter" data-level="4.4" data-path="decision-tree.html"><a href="decision-tree.html#model-interpretation-1"><i class="fa fa-check"></i><b>4.4</b> Model Interpretation</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="decision-tree.html"><a href="decision-tree.html#partial-dependence-plot-1"><i class="fa fa-check"></i><b>4.4.1</b> Partial Dependence Plot</a></li>
<li class="chapter" data-level="4.4.2" data-path="decision-tree.html"><a href="decision-tree.html#local-interpretable-model-agnostic-explanations-lime-1"><i class="fa fa-check"></i><b>4.4.2</b> Local Interpretable Model-agnostic Explanations (LIME)</a></li>
<li class="chapter" data-level="4.4.3" data-path="decision-tree.html"><a href="decision-tree.html#shapley-additive-explanations-1"><i class="fa fa-check"></i><b>4.4.3</b> Shapley Additive Explanations</a></li>
<li class="chapter" data-level="4.4.4" data-path="decision-tree.html"><a href="decision-tree.html#feature-importance-1"><i class="fa fa-check"></i><b>4.4.4</b> Feature Importance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-forest.html"><a href="random-forest.html"><i class="fa fa-check"></i><b>5</b> Random Forest</a></li>
<li class="chapter" data-level="6" data-path="reflections.html"><a href="reflections.html"><i class="fa fa-check"></i><b>6</b> Reflections</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Movie Box Office</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="decision-tree" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Decision Tree<a href="decision-tree.html#decision-tree" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="model-fitting-1" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Model Fitting<a href="decision-tree.html#model-fitting-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="model-visualization" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Model Visualization<a href="decision-tree.html#model-visualization" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="finalproj_files/figure-html/unnamed-chunk-27-1.png" width="672" />
The plot visualized our regression tree model. Since the size of the tree is so large, visualization does not work here. But we can find out each node’s information and splitting rule by checking the summary information of tree model.</p>
</div>
<div id="model-evaluation-1" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Model Evaluation<a href="decision-tree.html#model-evaluation-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>##        MSE      MAE R-Squared
## 1 1521.118 18.94823 0.5960518</code></pre>
<p>The evaluation table shows that regression tree model has much better performance than linear model no matter which criterion we use. Hence, in terms of accuracy, decision tree would be my choice.</p>
</div>
<div id="model-interpretation-1" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Model Interpretation<a href="decision-tree.html#model-interpretation-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="partial-dependence-plot-1" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Partial Dependence Plot<a href="decision-tree.html#partial-dependence-plot-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="finalproj_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Comparing the PDP of <code>rating</code> by using tree model and linear model, we find that the overall trend is the same, i.e., as <code>rating</code> goes up, predicted movie box office rises. And one difference is that, instead of being a straight line in linear model, we can observe that the line in tree model has ups and downs. This might be explained by the intrinsic nature of linear model: the effect of each feature on response variable alone is also linear. But in tree model, this is not that case, the mean box office of movies with higher rate is not necessarily larger than the mean box office of movies with lower rate. And clearly, the latter is what we observed more often in reality.
More insights that we can derive from this plot is that as <code>rating</code> increases from 4 to 6, movie box office does not increase a lot. This is probably because for those movies, people would watch and rate them online, but are not willing to buy tickets to watch them in theater. Hence, they all tend to have few box office. As for why there is a huge jump for <code>rating</code> from 7.8 to 8.3, I find it hard to give a reasonable guess.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-30-1.png" width="672" />
Again, the same part and difference between PDP of <code>runtime</code> by using tree model and linear model is similar to what we get at <code>rating</code> part: the overall trend is the same and we can get more insights from tree model. One more thing to notice is that, the range of movie box office in tree model for the two different features are not as much as it in linear model. This suggests that <code>rating</code> and <code>runtime</code> in tree model may contribute relatively equal explanations for variation in response variable.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-31-1.png" width="672" />
The PDP of certificate in tree model shows that PG and PG-13 movies tend to have more box office while Not Rated movies tend to have less box office. This is similar to the results obtained from linear model.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>The PDP of genre in tree model shows that action, animation, and horror movies are top three most popular types while drama, biography, and romance are the three types with least audience. In general, this is consistent with the conclusion by using linear model. But note that, the difference between each genre in tree model are far less than the difference in linear model. This indicates that <code>genre</code> in tree model is not as much important as it is in linear model.</p>
</div>
<div id="local-interpretable-model-agnostic-explanations-lime-1" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Local Interpretable Model-agnostic Explanations (LIME)<a href="decision-tree.html#local-interpretable-model-agnostic-explanations-lime-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="14%" />
<col width="15%" />
<col width="11%" />
<col width="13%" />
<col width="14%" />
<col width="20%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">model_intercept</th>
<th align="right">model_prediction</th>
<th align="left">feature</th>
<th align="right">feature_value</th>
<th align="right">feature_weight</th>
<th align="left">feature_desc</th>
<th align="right">prediction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-22.479</td>
<td align="right">133.157</td>
<td align="left">year</td>
<td align="right">92</td>
<td align="right">41.078</td>
<td align="left">year = 1996</td>
<td align="right">8.625</td>
</tr>
<tr class="even">
<td align="right">-22.479</td>
<td align="right">133.157</td>
<td align="left">certificate</td>
<td align="right">3</td>
<td align="right">61.044</td>
<td align="left">certificate = PG</td>
<td align="right">8.625</td>
</tr>
<tr class="odd">
<td align="right">-22.479</td>
<td align="right">133.157</td>
<td align="left">runtime</td>
<td align="right">100</td>
<td align="right">44.626</td>
<td align="left">runtime &lt;= 232</td>
<td align="right">8.625</td>
</tr>
<tr class="even">
<td align="right">-22.479</td>
<td align="right">133.157</td>
<td align="left">genre</td>
<td align="right">1</td>
<td align="right">33.229</td>
<td align="left">genre = Action</td>
<td align="right">8.625</td>
</tr>
<tr class="odd">
<td align="right">-22.479</td>
<td align="right">133.157</td>
<td align="left">rating</td>
<td align="right">5</td>
<td align="right">-24.341</td>
<td align="left">3.27 &lt; rating &lt;= 5.25</td>
<td align="right">8.625</td>
</tr>
</tbody>
</table>
<p><img src="finalproj_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>From the explanation table, we have that the local model for case 3649 is<br />
<span class="math inline">\(\hat{y}_{lime} = -30.148 -17.620 \cdot \mathbf{1}_{3.27 &lt; rating &lt;= 5.25}+55.755 \cdot \mathbf{1}_{certificate = PG}+31.348 \cdot \mathbf{1}_{genre = Action}+51.782 \cdot \mathbf{1}_{runtime &lt;= 232}+22.856 \cdot \mathbf{1}_{year = 1996}\)</span>
By comparing this result with lime model get in linear model, we find that even the direction of the effect of some features changed. For example, <span class="math inline">\(runtime\leq232\)</span> has a negative contribution to prediction in linear part, but it has a positive contribution here. Another difference is that the feature weight also changed a lot, <code>certificate</code> in linear part only rank as third one but has the largest weight here. Since the specific algorithm used to generate the local model is not clear to me, I could not provide an explanation for those difference. So how original model affects the fit of local model is waiting for more research.</p>
<pre><code>##   lime error original error
## 1  -33.19643     -13.082431
## 2  106.24943     -20.313573
## 3  -96.67111       8.675889
## 4  -33.11856       1.751440</code></pre>
<p>The residual table shows that our tree model also outperforms the local model. This may support my guess about trade off between interpretability and accuracy. Also note that the error for each case in tree model is less than it in linear model.</p>
<div id="gower-distance-1" class="section level4 hasAnchor" number="4.4.2.1">
<h4><span class="header-section-number">4.4.2.1</span> Gower Distance<a href="decision-tree.html#gower-distance-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><img src="finalproj_files/figure-html/unnamed-chunk-35-1.png" width="672" />
From the plot, we still have that as Gower distance increases, the variance of difference between pairs increases. One major distinction from linear part is that for pairs at the same difference level (the Gower distance between the pair is same), tree model tend to make more variant predictions compared with linear model. In my opinion, I think this might be an advantage since considering the features we include, two movies defined as similar will just have common characteristics in terms of rate, run time, genre, certificate, and published year. But for movies in which even all of the above features are same, in real case, they still tend to have very different box office as many other factors could have impact on, such as season, published area, and published volume in cinema every day.</p>
</div>
</div>
<div id="shapley-additive-explanations-1" class="section level3 hasAnchor" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Shapley Additive Explanations<a href="decision-tree.html#shapley-additive-explanations-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="finalproj_files/figure-html/unnamed-chunk-36-1.png" width="672" />
From the SHAP plot, case 10 has the most prediction value, <code>runtime</code> and <code>rating</code> contribute majority of the difference between mean <code>gross</code> of the 4 cases and prediction of case 10. By checking the feature value of each case in our sample, we find that case 10 has the highest rate and longest run time.<br />
On the other hand, case 4464 has the least prediction value, <code>year</code> is the main factor caused the low prediction. And we can see that case 4464 is the oldest movie which is published in 1973.<br />
By compare the interpretation provided by SHAP and by LIME, they seems to be not consistent with each other in explanations for some features. Hence, the question is which one provide a more reasonable interpretation or it depends on situation and purpose.</p>
</div>
<div id="feature-importance-1" class="section level3 hasAnchor" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> Feature Importance<a href="decision-tree.html#feature-importance-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="finalproj_files/figure-html/unnamed-chunk-37-1.png" width="672" />
The feature importance plot shows that <code>year</code> is the most important feature while <code>genre</code> is the least important feature. This seems to be consistent with result obtained from partial dependence plot.<br />
When compared with feature importance in linear model, they are quiet different. <code>Year</code> in linear model is not as important as it is in tree model. My opinion is that the relationship between <code>year</code> and <code>gross</code> is not linear but will fluctuate, hence linear model could not capture the impact of <code>year</code>. But linear constraint is not a problem for tree model, hence tree model could utilize this feature well.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="random-forest.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/hzha3/Stat_5293_FInal_Project/edit/main/model2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/hzha3/Stat_5293_FInal_Project/blob/main/model2.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
