<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Random Forest | Movie Box Office</title>
  <meta name="description" content="Chapter 5 Random Forest | Movie Box Office" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Random Forest | Movie Box Office" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Random Forest | Movie Box Office" />
  
  
  

<meta name="author" content="Hongwei Zha" />


<meta name="date" content="2023-04-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="decision-tree.html"/>
<link rel="next" href="reflections.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">IMDB</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Proposal</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data"><i class="fa fa-check"></i><b>1.1</b> Data</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#modeling-goal"><i class="fa fa-check"></i><b>1.2</b> Modeling Goal</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#models"><i class="fa fa-check"></i><b>1.3</b> Models</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-pre-processing.html"><a href="data-pre-processing.html"><i class="fa fa-check"></i><b>2</b> Data pre-processing</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-pre-processing.html"><a href="data-pre-processing.html#data-dictionary"><i class="fa fa-check"></i><b>2.1</b> Data Dictionary</a></li>
<li class="chapter" data-level="2.2" data-path="data-pre-processing.html"><a href="data-pre-processing.html#data-summary"><i class="fa fa-check"></i><b>2.2</b> Data Summary</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-pre-processing.html"><a href="data-pre-processing.html#data-statistics"><i class="fa fa-check"></i><b>2.2.1</b> Data Statistics</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-pre-processing.html"><a href="data-pre-processing.html#visualizing-missing-values"><i class="fa fa-check"></i><b>2.2.2</b> Visualizing Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-pre-processing.html"><a href="data-pre-processing.html#box-office-vs-genre"><i class="fa fa-check"></i><b>2.3</b> Box Office Vs Genre</a></li>
<li class="chapter" data-level="2.4" data-path="data-pre-processing.html"><a href="data-pre-processing.html#box-office-vs-rating-certificate"><i class="fa fa-check"></i><b>2.4</b> Box Office Vs Rating &amp; Certificate</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>3</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="linear-regression.html"><a href="linear-regression.html#model-fitting"><i class="fa fa-check"></i><b>3.1</b> Model Fitting</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="linear-regression.html"><a href="linear-regression.html#model-summary"><i class="fa fa-check"></i><b>3.1.1</b> Model Summary</a></li>
<li class="chapter" data-level="3.1.2" data-path="linear-regression.html"><a href="linear-regression.html#check-linearity"><i class="fa fa-check"></i><b>3.1.2</b> Check Linearity</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="linear-regression.html"><a href="linear-regression.html#model-evaluation"><i class="fa fa-check"></i><b>3.2</b> Model Evaluation</a></li>
<li class="chapter" data-level="3.3" data-path="linear-regression.html"><a href="linear-regression.html#model-interpretation"><i class="fa fa-check"></i><b>3.3</b> Model Interpretation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="linear-regression.html"><a href="linear-regression.html#partial-dependence-plot"><i class="fa fa-check"></i><b>3.3.1</b> Partial Dependence Plot</a></li>
<li class="chapter" data-level="3.3.2" data-path="linear-regression.html"><a href="linear-regression.html#local-interpretable-model-agnostic-explanations-lime"><i class="fa fa-check"></i><b>3.3.2</b> Local Interpretable Model-agnostic Explanations (LIME)</a></li>
<li class="chapter" data-level="3.3.3" data-path="linear-regression.html"><a href="linear-regression.html#shapley-additive-explanations"><i class="fa fa-check"></i><b>3.3.3</b> Shapley Additive Explanations</a></li>
<li class="chapter" data-level="3.3.4" data-path="linear-regression.html"><a href="linear-regression.html#feature-importance"><i class="fa fa-check"></i><b>3.3.4</b> Feature Importance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="decision-tree.html"><a href="decision-tree.html"><i class="fa fa-check"></i><b>4</b> Decision Tree</a>
<ul>
<li class="chapter" data-level="4.1" data-path="decision-tree.html"><a href="decision-tree.html#model-visualization"><i class="fa fa-check"></i><b>4.1</b> Model Visualization</a></li>
<li class="chapter" data-level="4.2" data-path="decision-tree.html"><a href="decision-tree.html#model-evaluation-1"><i class="fa fa-check"></i><b>4.2</b> Model Evaluation</a></li>
<li class="chapter" data-level="4.3" data-path="decision-tree.html"><a href="decision-tree.html#model-interpretation-1"><i class="fa fa-check"></i><b>4.3</b> Model Interpretation</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="decision-tree.html"><a href="decision-tree.html#partial-dependence-plot-1"><i class="fa fa-check"></i><b>4.3.1</b> Partial Dependence Plot</a></li>
<li class="chapter" data-level="4.3.2" data-path="decision-tree.html"><a href="decision-tree.html#local-interpretable-model-agnostic-explanations-lime-1"><i class="fa fa-check"></i><b>4.3.2</b> Local Interpretable Model-agnostic Explanations (LIME)</a></li>
<li class="chapter" data-level="4.3.3" data-path="decision-tree.html"><a href="decision-tree.html#shapley-additive-explanations-1"><i class="fa fa-check"></i><b>4.3.3</b> Shapley Additive Explanations</a></li>
<li class="chapter" data-level="4.3.4" data-path="decision-tree.html"><a href="decision-tree.html#feature-importance-1"><i class="fa fa-check"></i><b>4.3.4</b> Feature Importance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-forest.html"><a href="random-forest.html"><i class="fa fa-check"></i><b>5</b> Random Forest</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-forest.html"><a href="random-forest.html#model-fitting-1"><i class="fa fa-check"></i><b>5.1</b> Model Fitting</a></li>
<li class="chapter" data-level="5.2" data-path="random-forest.html"><a href="random-forest.html#model-evaluation-2"><i class="fa fa-check"></i><b>5.2</b> Model Evaluation</a></li>
<li class="chapter" data-level="5.3" data-path="random-forest.html"><a href="random-forest.html#model-interpretation-2"><i class="fa fa-check"></i><b>5.3</b> Model Interpretation</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-forest.html"><a href="random-forest.html#partial-dependence-plot-2"><i class="fa fa-check"></i><b>5.3.1</b> Partial Dependence Plot</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-forest.html"><a href="random-forest.html#local-interpretable-model-agnostic-explanations-lime-2"><i class="fa fa-check"></i><b>5.3.2</b> Local Interpretable Model-agnostic Explanations (LIME)</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-forest.html"><a href="random-forest.html#shapley-additive-explanations-2"><i class="fa fa-check"></i><b>5.3.3</b> Shapley Additive Explanations</a></li>
<li class="chapter" data-level="5.3.4" data-path="random-forest.html"><a href="random-forest.html#feature-importance-2"><i class="fa fa-check"></i><b>5.3.4</b> Feature Importance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="reflections.html"><a href="reflections.html"><i class="fa fa-check"></i><b>6</b> Reflections</a>
<ul>
<li class="chapter" data-level="6.1" data-path="reflections.html"><a href="reflections.html#takeaways"><i class="fa fa-check"></i><b>6.1</b> Takeaways</a></li>
<li class="chapter" data-level="6.2" data-path="reflections.html"><a href="reflections.html#limitation-and-future-direction"><i class="fa fa-check"></i><b>6.2</b> Limitation and Future Direction</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Movie Box Office</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="random-forest" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Random Forest<a href="random-forest.html#random-forest" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="model-fitting-1" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Model Fitting<a href="random-forest.html#model-fitting-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## 
## Call:
##  randomForest(formula = gross ~ year + certificate + runtime +      genre + rating, data = train_dat, importance = TRUE) 
##                Type of random forest: regression
##                      Number of trees: 500
## No. of variables tried at each split: 1
## 
##           Mean of squared residuals: 1496.916
##                     % Var explained: 62.24</code></pre>
<p>We can read from the information of random forest model that the R-Squared value on the training set is 0.6224, which is less than the R-Squared value of tree model on the training set 0.7757, but is larger than the R-Squared value of linear model on the training set 0.2641. However, considering the tree model tend to be overfitting, I should compare their performance on the test set.</p>
</div>
<div id="model-evaluation-2" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Model Evaluation<a href="random-forest.html#model-evaluation-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>##        MSE      MAE R-Squared
## 1 1445.054 20.93738 0.6162513</code></pre>
<p>The evaluation table shows random forest’s performance on the test set. Random forest has slightly larger R-Squared value than tree model and much larger R-Squared value than linear model. But since the R-Squared value only increased from 0.5838 to 0.6163, I do not think random forest and tree model has very different performance.</p>
</div>
<div id="model-interpretation-2" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Model Interpretation<a href="random-forest.html#model-interpretation-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="partial-dependence-plot-2" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Partial Dependence Plot<a href="random-forest.html#partial-dependence-plot-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="finalproj_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>Again the PDP of rating shows that the overall trend is the same as PDP in linear model and tree model: as <code>rating</code> goes up, predicted movie box office rises. However, we can note that the range of movie box office is much larger than the range of movie box office in linear and tree model. This shows that <code>rating</code> is much more important in random forest than as it is in linear and tree model. And this is what I expected since intuitively, high quality movies will attract more people to see.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>The PDP of <code>runtime</code> in random forest leads to similar conclusion: movie with longer run time tend to have more box office. But note that the range of box office is almost a half of it in <code>rating</code> part, this suggests that <code>runtime</code> is far less important than <code>rating</code> in random forest model. We did not observe this difference in tree model and we indeed observed a little difference in linear model but it is not obvious as it is in random forest model. In my opinion, I support the conclusion that <code>rating</code> is much more important than <code>runtime</code> since length of a movie is never a deterministic factor of whether it is a good or bad movie, hence less impact on the movie box office.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>The PDP of <code>certificate</code> in random forest model shows that PG-13 and PG movies tend to have more box office while Not Rated movies tend to have less box office. This is similar to the results obtained from linear and tree model.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>The PDP of <code>genre</code> in random forest model shows that animation, action, and adventure movies are top three most popular types while drama, biography, and romance are the three types with least audience. This is consistent with the conclusion obtained from linear and tree model. And in terms of the difference between each genre, the plot is more like what we observed in tree model part.</p>
</div>
<div id="local-interpretable-model-agnostic-explanations-lime-2" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Local Interpretable Model-agnostic Explanations (LIME)<a href="random-forest.html#local-interpretable-model-agnostic-explanations-lime-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="14%" />
<col width="15%" />
<col width="11%" />
<col width="13%" />
<col width="14%" />
<col width="20%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">model_intercept</th>
<th align="right">model_prediction</th>
<th align="left">feature</th>
<th align="right">feature_value</th>
<th align="right">feature_weight</th>
<th align="left">feature_desc</th>
<th align="right">prediction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">13.233</td>
<td align="right">57.499</td>
<td align="left">year</td>
<td align="right">27</td>
<td align="right">-1.574</td>
<td align="left">year = 1996</td>
<td align="right">25.02</td>
</tr>
<tr class="even">
<td align="right">13.233</td>
<td align="right">57.499</td>
<td align="left">certificate</td>
<td align="right">3</td>
<td align="right">25.748</td>
<td align="left">certificate = PG</td>
<td align="right">25.02</td>
</tr>
<tr class="odd">
<td align="right">13.233</td>
<td align="right">57.499</td>
<td align="left">runtime</td>
<td align="right">100</td>
<td align="right">15.070</td>
<td align="left">runtime &lt;= 232</td>
<td align="right">25.02</td>
</tr>
<tr class="even">
<td align="right">13.233</td>
<td align="right">57.499</td>
<td align="left">genre</td>
<td align="right">1</td>
<td align="right">17.308</td>
<td align="left">genre = Action</td>
<td align="right">25.02</td>
</tr>
<tr class="odd">
<td align="right">13.233</td>
<td align="right">57.499</td>
<td align="left">rating</td>
<td align="right">5</td>
<td align="right">-12.285</td>
<td align="left">3.27 &lt; rating &lt;= 5.25</td>
<td align="right">25.02</td>
</tr>
</tbody>
</table>
<p><img src="finalproj_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>From the explanation table, we have that the local model for case 3649 is <span class="math inline">\(\hat{y}_{lime} = 77.399 -12.144 \cdot \mathbf{1}_{3.27 &lt; rating &lt;= 5.25}+26.044 \cdot \mathbf{1}_{certificate = PG}+19.739 \cdot \mathbf{1}_{genre = Action}-49.789 \cdot \mathbf{1}_{runtime &lt;= 232}+3.814 \cdot \mathbf{1}_{year = 1996}\)</span>. By doing comparison with the results from linear and tree model, we find that in terms of direction, linear model and random forest give the same interpretation for case 3649; in terms of magnitude, three models generated pairwise different local models. And we can also find some common place resembled by all three models: <code>runtime</code> = PG and <code>genre</code> = Action has similar scale positive contribution in all three models.</p>
<pre><code>##   lime error original error
## 1  -38.81143      -7.771431
## 2  125.96443      76.427427
## 3  -47.76211      -8.010111
## 4  -18.66056      -7.084560</code></pre>
<p>The residual table shows that our random forest model also outperforms its local model. Also note that random forest makes slightly less error than tree model did for case 6155 and case 3649, and make larger error for case 10 and case 4464. This supports the idea that random forest model does not have much better performance than tree model in terms of accuracy.</p>
<div id="gower-distance-2" class="section level4 hasAnchor" number="5.3.2.1">
<h4><span class="header-section-number">5.3.2.1</span> Gower Distance<a href="random-forest.html#gower-distance-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><img src="finalproj_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>Again we read from the plot that as Gower distance increases, the variance of difference between pairs increases. And note that the range of difference is similar to the range obtained in linear model, and it is about a half of the range get in tree model. As I mentioned in tree model part, I think more variance makes more sense in real situation, thus maybe random forest does not do as well as tree model for this regard.</p>
</div>
</div>
<div id="shapley-additive-explanations-2" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Shapley Additive Explanations<a href="random-forest.html#shapley-additive-explanations-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="finalproj_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Since case 10 has the most predicted value and case 4464 has the least predicted value in random forest model, we focus on these two cases. From the SHAP plot, <code>runtime</code> and <code>rating</code> contribute majority of the difference between mean <code>gross</code> and prediction of case 10; <code>year</code> is a main factor caused the low prediction for case 4464. This is basically the same as what we derived from tree model. Then, comparing the interpretation provided by SHAP and by LIME, again, they are not consistent with each other for some features. Still taking case 10 as an example, LIME implies that <code>runtime</code> has a negative effect on predicted value while SHAP indicates that <code>runtime</code> has a positive effect. Another point that I want to mention is that if the Shapley value seem to have some randomness, i.e., if I do not fix a seed, every time I run the code, I get different SHAP plot.</p>
</div>
<div id="feature-importance-2" class="section level3 hasAnchor" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Feature Importance<a href="random-forest.html#feature-importance-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="finalproj_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>The feature importance plot shows that <code>certificate</code> is the most important feature while <code>year</code> is the least important feature. This seems to be not consistent with result obtained from partial dependence plot. For example, from PDP, <code>rating</code> is more important than <code>runtime</code> and <code>certificate</code> as it caused more variation in movie box office. And we also note that the feature importance in three models are different from each other no matter using PDP or some other methods. But in terms of percentage, I think <code>rating</code>’s importance does not change a lot from model to model.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="decision-tree.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reflections.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/hzha3/Stat_5293_FInal_Project/edit/main/model3.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/hzha3/Stat_5293_FInal_Project/blob/main/model3.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
